bpf: Guard MODULES dependencies
This architecture no longer uses the module_alloc and module_memfree
functions for BPF_JIT, futhermore, MODULES support is disbled on
this kernel making them even more useless.

Guard BPF functions used to call module_(alloc|memfree) to avoid
the following compilation error:

kernel/bpf/core.o: In function `bpf_jit_alloc_exec':
core.c:(.text+0xbb4): undefined reference to `module_alloc'
kernel/bpf/core.o: In function `bpf_jit_free_exec':
core.c:(.text+0xbc8): undefined reference to `module_memfree'

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>